# fly.toml app configuration file generated for marcus-ebmldg on 2026-08-07T11:01:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marcus-ebmldg'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile"
  
[processes]
  app = "python bot.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
